# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ request-management ]
  pull_request:
    branches: [ request-management ]

jobs:
  build-x-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew -Pprod clean bootJar -x test
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.4
      with:
        node-version: 12.19.0
    - name: Install dependecies
      run:  cd frontend && npm install
    - name: Build frontend production profile
      run:  cd frontend && npm run build:prod

